### PR TITLE
merge-parent-keys Add mergeEnabled boolean flag 

### PR DESCRIPTION
**Pull request by billneff79**
Related to issue #3, add mergeEnabled boolean flag to merge provided key…values with parent key values, giving precedence to parent values.

### CODE REVIEW

**Comment by pl12133** [comment]
Some thoughts:

1. This would be a breaking change if an App were providing a value for `mergeEnabled`, as unlikely as that might be.
2. Increases the API surface area of the `<Provider>`.
3. Bundle size increase.

The Provider is so simple it could be worth making a separate one. Having a separate component would let this Component and the `deepAssign` function get tree-shaken out, so this wouldn't affect bundle size on existing Apps:

```js
class MergingProvider extends Component {
	getChildContext() {
		let context = {}, props = this.props;
		for (let i in props) if (i !== 'children') {
			context[i] = deepAssign(this.context[i], props[i]);
 	  	}
		return context;
	}

	render(props) {
		return props.children[0];
	}
}
```

Let me know what you think.

**Comment by billneff79** [comment]
I was thinking the same thing about it being a separate component for tree shaking purposes.  I'll do that.

**Comment by billneff79** [comment]
OK, I added `<MergingProvider/>` and `mergingProvide()` as new named exports instead of messing with the existing `<Provider/>` and `provide()`.  Check out the rich-diff of the new README and unit tests for details and let me know what you think.  It adds 200b to the build size, but if you use tree shaking and don't use the new functionality, you shouldn't see any impact.  I think we could release this as a minor change instead of major.

**Review by pl12133 — APPROVED** [review]
Look's great! The non-merging nature of `Provider` has bit me a couple of times so it is great to have this option.

**Pull request merged**
